config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :user
  devise_scope :user do
    get 'signup', :to => 'devise/registrations#new'
    get 'login', :to => 'devise/sessions#new'
    get 'signout', :to => 'devise/sessions#destroy'
  end

  root 'boards#index'

  post "b", to: "boards#create", as: "boards"

  get "b/:id", to: "boards#show", as: "board"
  delete "b/:id", to: "boards#destroy"

  get "b/:board_id/files", to: "sitefiles#index", as: "sitefiles"
  post "b/:board_id/files", to: "sitefiles#create"

end

app/models/board.rb
class Board < ActiveRecord::Base

  belongs_to :user
  has_many :sitefiles, dependent: :destroy

  validates :stub, uniqueness: true

  before_validation :set_stub

  def to_param
    self.stub
  end

protected

  def set_stub
    self.stub ||= SecureRandom.hex[0..6].downcase
  end

end

app/models/sitefile.rb
class Sitefile < ActiveRecord::Base

  belongs_to :board
  belongs_to :user

  mount_uploader :sitefile, SitefileUploader

  validates :stub, uniqueness: true

  before_validation :set_stub

  def as_json
    {
      id: self.stub,
      url: self.sitefile.url,
      url640: self.sitefile.url,
      url1024: self.sitefile.url,
      createdAt: self.created_at,
    }
  end

protected

  def set_stub
    self.stub ||= SecureRandom.hex.downcase
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :boards

  def name
    self.email.split("@")[0]
  end

  def is_admin?
    self.id == 1
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  def index
    if user_signed_in?
      @boards = current_user.boards.order("created_at DESC")
    else
      render template: "boards/outside"
    end
  end

  def create
    board = current_user.boards.create
    redirect_to board
  end

  def show
    @board = Board.find_by_stub(params[:id])

    if @board.nil?
      render text: "no board found"
    end
  end

  def destroy
    @board = current_user.boards.find_by_stub(params[:id])
    @board.destroy!

    redirect_to root_url
  end

end

app/controllers/sitefiles_controller.rb
class SitefilesController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: "create"

  def index
    board = Board.find_by_stub(params[:board_id])
    sitefiles = board.sitefiles.order("created_at ASC")

    render json: sitefiles.as_json
  end

  def create
    board = Board.find_by_stub(params[:board_id])

    if current_user.nil? || current_user != board.user
      render json: {success: false}
      return
    end

    sitefile = board.sitefiles.new
    sitefile.user = current_user
    sitefile.sitefile = params[:files]
    sitefile.extension = File.extname(params[:files].original_filename)
    sitefile.save!

    render json: {success: true}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/views/boards/index.html.erb
<%= button_to "New Board", boards_url(:method => :post), class: "btn lead-button" %>

<div class="row board-row">
  <div class="col-sm-8">
    Boards
  </div>
  <div class="col-sm-1">
    Files
  </div>
  <div class="col-sm-2">
    Created
  </div>
  <div class="col-sm-1">
  </div>
</div>

<% @boards.each do |board| %>
  <div class="row board-row">
    <div class="col-sm-8">
      <%= link_to board.stub, board_url(board) %>
    </div>
    <div class="col-sm-1">
      <%= board.sitefiles.count %>
    </div>
    <div class="col-sm-2">
      <%= time_ago_in_words board.created_at %>
    </div>
    <div class="col-sm-1">
      <%= button_to "delete", board_url(board), method: "delete", class: "btn" %>
    </div>
  </div>
<% end %>

app/views/boards/outside.html.erb
<div id="demo">
  <h1>
    Pasteboard
  </h1>
  <p class="lead centered">
    Paste images you want to show people.
  </p>
</div>

app/views/boards/show.html.erb
<% if current_user && @board && @board.user == current_user %>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <div id="dropbox">
      <p>
        Drag files here<br>
        <small>or paste if you use Chrome</small>
      </p>
    </div>

    <div id="last-upload">
      Uploading paste....
    </div>
  </div>
</div>

<% end %>

<div class="row">
  <div class="col-sm-12">
    <div id="images" class="clearfix">
    </div>
  </div>
</div>

<script type="text/template" id="thumb-template">
<div class="image-wrapper">
  <a href="<%%= url %>" class="thumbnail-full">
    <img src="<%%= url640 %>" class="img-responsive">
  </a>
</div>
</script>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.4.4/underscore-min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.0.0/backbone-min.js"></script>

<%= javascript_include_tag "jqueryfiledrop" %>
<%= javascript_include_tag "dropbox" %>

<script type="text/javascript">
  window.filesUrl = "<%= sitefiles_url(@board) %>";
</script>

<%= javascript_include_tag "board" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pasteboard</title>
  <%= stylesheet_link_tag "//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<div class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pasteboard</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li>
            <%= link_to "Sign Out", signout_url %>
          </li>
        <% else %>
          <li>
            <%= link_to "Sign Up", signup_url %>
          </li>
          <li>
            <%= link_to "Log In", login_url %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="container bodyctn">
  <%= yield %>
</div>

<%= javascript_include_tag "//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js" %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-51191800-1', 'pasteboard.io');
  ga('send', 'pageview');

</script>

</body>
</html>